[2024-06-26T22:37:44.641+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T22:37:44.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_example_v3.second_task manual__2024-06-26T22:37:43.134313+00:00 [queued]>
[2024-06-26T22:37:44.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_example_v3.second_task manual__2024-06-26T22:37:43.134313+00:00 [queued]>
[2024-06-26T22:37:44.656+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-26T22:37:44.660+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): second_task> on 2024-06-26 22:37:43.134313+00:00
[2024-06-26T22:37:44.663+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_example_v3', 'second_task', 'manual__2024-06-26T22:37:43.134313+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/first_example.py', '--cfg-path', '/tmp/tmp40f_9ait']
[2024-06-26T22:37:44.664+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6235) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-26T22:37:44.664+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask second_task
[2024-06-26T22:37:44.664+0000] {standard_task_runner.py:63} INFO - Started process 6236 to run task
[2024-06-26T22:37:44.681+0000] {task_command.py:426} INFO - Running <TaskInstance: first_example_v3.second_task manual__2024-06-26T22:37:43.134313+00:00 [running]> on host 6f85ce718b3c
[2024-06-26T22:37:44.706+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nash5657' AIRFLOW_CTX_DAG_ID='first_example_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T22:37:43.134313+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T22:37:43.134313+00:00'
[2024-06-26T22:37:44.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T22:37:44.711+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-26T22:37:44.712+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "I am the second task"']
[2024-06-26T22:37:44.714+0000] {subprocess.py:86} INFO - Output:
[2024-06-26T22:37:44.715+0000] {subprocess.py:93} INFO - I am the second task
[2024-06-26T22:37:44.715+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-26T22:37:44.715+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T22:37:44.724+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=first_example_v3, task_id=second_task, run_id=manual__2024-06-26T22:37:43.134313+00:00, execution_date=20240626T223743, start_date=20240626T223744, end_date=20240626T223744
[2024-06-26T22:37:44.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T22:37:44.773+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
